spring.application.name=brachymusicstore

spring.datasource.url=jdbc:mysql://localhost:3306/brachymusicstore
spring.datasource.username=root
spring.datasource.password=Edzon263#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
